### ISSUE TITLE
backends/session does not accept any options

### ISSUE THREAD

**Issue by g7s** [duct-framework/middleware.buddy#1]
Hi,
the code [here](https://github.com/duct-framework/middleware.buddy/blob/master/src/duct/middleware/buddy.clj#L8) suggests that the `backends/session` cannot accept any options and thus one can pass neither `authorization-fn` nor `auth-fn` as [options](https://github.com/funcool/buddy-auth/blob/master/src/buddy/auth/backends/session.clj#L23)

**Comment by weavejester** [comment]
Weird, I'm not sure why I cut out the argument in the first place.
