### ISSUE TITLE
Docs ahead of release

### ISSUE THREAD

**Issue by stelcodes** [duct-framework/middleware.buddy#5]
Hi weavejester! I noticed that the current release doesn't include the commit for the  `:duct.middleware.buddy/authorization` integrant key methods. I saw that the pull request was merged a few months ago. Is a new release in order? Just wanted to point this out as it could be a point of confusion for others.

p.s. thanks for all the beautiful data driven libraries!!

**Comment by weavejester** [comment]
Released 0.2.0. Sorry about the delay.
